/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package patterns;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testApp()
    {
        App classUnderTest = new App();
        StringTester test = new StringTester();

        test.stringDrink();
        test.stringInverter();
        test.stringCaseChanger();
        test.stringReplacer();
        test.stringRecipe();
        test.transformerGroup();
        test.transformerComposite();
        test.happyHour();
        test.addObserver();
        test.removeObserver();
    }
}
